apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: "true"
    opsrc-provider: redhat
  name: ${REPO_NAME}-registry
  namespace: openshift-${REPO_NAME}
spec:
  image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: Exists
        weight: 1
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
  displayName: ${REPO_NAME}
  icon:
    base64data: ''
    mediatype: ''
  publisher: Red Hat
  sourceType: grpc
